### ISSUE TITLE
problem with make

### ISSUE THREAD

**Issue by boatsafe** [pinkavaj/gr-scan#2]
hello   I have unzipped the gr-scan file and then using terminal run Make but I get an error 
This is the response I get in terminal ..........................................................

g++ -DVERSION="\"gr-scan 2013102901\""  -Wall -lgnuradio-filter -lgnuradio-blocks -lgnuradio-pmt -lgnuradio-fft -lgnuradio-runtime -lgnuradio-osmosdr -lboost_system -O2 -s -Wno-unused-function -o gr-scan main.cpp
In file included from main.cpp:23:0:
topblock.hpp:23:32: fatal error: gnuradio/top_block.h: No such file or directory
 #include <gnuradio/top_block.h>
                                ^
compilation terminated.
make: **\* [gr-scan] Error 1
Not sure what I am doing wrong  Hope I can get some help 
Thanks Graham

**Comment by pinkavaj** [comment]
You probably does not have installed development package for GnuRadio

**Comment by albedo039** [comment]
i do have the same problem that boatsfe..
is there an howto that explain  in details how to install correctly development package and run good make ?
thanks to all

**Comment by albedo039** [comment]
all troubles are resolved for me in a ubuntu 16.04lts and gnuradio installed with rtlsdr tools...
it's ok....scan works good..

**Comment by NHB642** [comment]
Hello, I would like to ask whether this example can achieve a wide range of spectrum scanning, such as 300-500m, and whether it can be used for usrp B200，Thanks

**Comment by pinkavaj** [comment]
This question is not related to problem discussed in this issue, please consider create new issue or better ask this on some ML.
